### ISSUE TITLE
Adding new PC by agent

### ISSUE THREAD

**Issue by srenat** [booskit-codes/PyITAgent#5]
Good day, 
Ive got problems with some computers with the following error:

An error occurred in the PyITAgent script: None
Error occured on computer: ALA-AUT-MB-007
Error occured on user: A*****M\Z*.Z*******ova
Error occured on version: v1.5

Traceback (most recent call last):
  File "PyITAgent\main.py", line 13, in main
  File "C:\Users\ZH6558~1.ZHI\AppData\Local\Temp\_MEI256042\runtime\client.py", line 19, in runtime
    self.metadata['manufacturer_id'], self.hardware['manufacturer_name'] = asset_manager.manufacturer.get_or_create_manufacturer()
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZH6558~1.ZHI\AppData\Local\Temp\_MEI256042\models\assets\manufacturer.py", line 50, in get_or_create_manufacturer
    success = self.post_manufacturer(self.manufacturer_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZH6558~1.ZHI\AppData\Local\Temp\_MEI256042\models\assets\manufacturer.py", line 44, in post_manufacturer
    raise Exception(f"Failed to post manufacturer: {response.get('messages')}")
Exception: Failed to post manufacturer: {'name': ['The name has already been taken.']}

**Comment by b00skit** [comment]
Solved.
#7
